# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'WXChat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   use_frameworks!

  # Pods for WXChat
pod 'EaseUI', :git => 'https://github.com/easemob/easeui-ios-hyphenate-cocoapods.git'
pod 'MMWebView'
pod 'FMDB'
pod 'YYText'
pod 'UUActionSheet'
pod 'UUButton'
pod 'MLLabel'
pod 'AMap3DMap'
pod 'CWLateralSlide', '~> 1.6.3'
pod 'SDAutoLayout'
pod 'Masonry'
pod 'AFNetworking'
pod 'YYModel'
pod 'SnapKit'
pod 'HMSegmentedControl'
pod 'IQKeyboardManager'
pod ''
end
